### PR TITLE
Remove Jenkins config and update readme

### PR DESCRIPTION
**Pull request by i-like-robots**
We no longer need to store the Jenkins job config.

We can probably change the command to `make run` too =)

### CODE REVIEW

**Comment by matthew-andrews** [comment]
is it running in travis now?

**Comment by i-like-robots** [comment]
It's still in Jenkins, just no need to manage the config in Git anymore.

**Comment by matthew-andrews** [comment]
why not?

**Comment by i-like-robots** [comment]
The config was being used to manage data. I suppose there is no harm keeping it in a purely config capacity ;-)

**Comment by matthew-andrews** [comment]
yes please … if our jenkins gets lost would be nice to have a backup somewhere logic … :)

**Comment by i-like-robots** [comment]
#18 \0/

**Pull request merged**
